title: Alex Stowe # your name (or website title) here
logo: "/images/1660224710713.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Business Systems Analyst and Masters student at Georgia Tech University in Data Analytics. Learning and exploring different avenues of data analysis, data visualization and coding. 
  <br><br>
  Outside of data science and my career, I also produce electronic music and am actively learning how to create generative artworks via coding. 
  <br><br>
  <a href="https://www.linkedin.com/in/alex-stowe-295578138/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/alex-stowe-295578138/">View My Spotify</a> 
  
theme: jekyll-theme-minimal
background-color: gb(255,255,25);
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
